###############
# Definitions #
###############

stages:
  - quality
  - build
  - deploy
  - cleanup

before_script:
  - export TAG_VERSION=${CI_COMMIT_REF_NAME}
  - export PROJECT_NAME=gpe
  - export DOCKER_USER=bastienlalos
  - export DOCKER_PASSWORD=21dc356a-98d3-487b-ad0a-9040eb688dd7

##############
#    Jobs    #
##############

# Check javascript syntax rules
linter:
  image: node:11.7
  stage: quality
  script:
    - npm install --loglevel error
    - npm run lint

# Run unit tests
unit-test:
  image: node:11.7
  stage: quality
  script:
    - npm install --loglevel error
    - npm test

# ========== ONLY FOR TAGS x.x.x =========

# Construct node images
build:
  tags:
    - gpe-runner
  stage: build
  only:
    - /^version-([0-9]+\.){2}[0-9]+$/
  except:
    - branches
  script:
    - docker build -t $PROJECT_NAME-api:$TAG_VERSION .

# Push image to registry
publish:
  tags:
    - gpe-runner
  stage: build
  only:
    - /^version-([0-9]+\.){2}[0-9]+$/
  except:
    - branches
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker tag $PROJECT_NAME-api:$TAG_VERSION $DOCKER_USER/$PROJECT_NAME-api:latest
    - docker push $DOCKER_USER/$PROJECT_NAME-api:latest

# Deploy to swarm
deploy:
  tags:
    - gpe-runner
  stage: deploy
  only:
    - /^version-([0-9]+\.){2}[0-9]+$/
  except:
    - branches
  script:
    - docker stack deploy -c docker/docker-compose.yml $PROJECT_NAME

# clean docker
clean-docker:
  tags:
    - gpe-runner
  stage: cleanup
  only:
    - /^docker-([0-9]+\.){2}[0-9]+$/
    - /^version-([0-9]+\.){2}[0-9]+$/
  except:
    - branches
  script:
    - docker system prune -f