###############
# Definitions #
###############

stages:
  - quality
  - build
  - deploy

before_script:
  - export TAG_VERSION=${CI_COMMIT_REF_NAME}
  - export PROJECT_NAME=gpe
  - export REPO=bastienlalos

##############
#    Jobs    #
##############

# Check javascript syntax rules
linter:
  image: node:11.7
  stage: quality
  script:
    - npm install --loglevel error
    - npm run lint

# Run unit tests
unit-test:
  image: node:11.7
  stage: quality
  script:
    - npm install --loglevel error
    - npm test

# ========== ONLY FOR TAGS x.x.x =========

# Construct node images
build:
  tags: 
    - gpe-runner
  stage: build
  only:
    - /^version-([0-9]+\.){2}[0-9]+$/
  except:
    - branches
  script:
    - docker build -t $PROJECT_NAME-api:$TAG_VERSION .

# Push image to registry
publish:
  tags: 
    - gpe-runner
  stage: build
  only:
    - /^version-([0-9]+\.){2}[0-9]+$/
  except:
    - branches
  script:
    - docker tag $PROJECT_NAME-api:$TAG_VERSION $REPO/$PROJECT_NAME-api:latest

# Deploy to swarm
deploy:
  tags: 
    - gpe-runner
  stage: deploy
  only:
    - /^version-([0-9]+\.){2}[0-9]+$/
  except:
    - branches
  script:
    - docker stack deploy -c docker/docker-compose.yml $PROJECT_NAME
