version: "3.6"

services:
    api:
        image: bastienlalos/gpe-api:latest
        environment:
            - ENV=PROD
            - TAGS=https
            - DATABASE_HOST=dbapi
            - DATABASE_PORT=3306
            - DATABASE_TYPE=mysql
            - DATABASE_USER=root
            - DATABASE_PASSWORD_FILE=/run/secrets/api_mysql_root
            - DATABASE_SCHEMA=GPE
        secrets:
            - api_mysql_root
        ports:
            - 3000:3000
        networks:
            - gpe-net
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 30s

secrets:
    api_mysql_root:
        external: true

networks:
    gpe-net:
        external: true

